use serde::Deserialize;
use std::fmt::Write;
use std::path::PathBuf;

#[derive(Deserialize)]
struct PinFile {
    pins: Vec<Pin>,
}

#[derive(Deserialize)]
struct Pin {
    name: String,
    port: u8,
    pin: u8,
    port_periph: String,
    pfs_method: String,
    pfs_type: String,
    #[serde(default)]
    pfs_index: usize,
    #[serde(default)]
    input_only: bool,
    packages: Vec<String>,
}

fn main() {
    println!("cargo:rerun-if-changed=pins.toml");
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let pins_toml = std::fs::read_to_string("pins.toml").expect("pins.toml not found");
    let pin_file: PinFile = toml::from_str(&pins_toml).expect("pins.toml not valid TOML");

    /*
     * Determine which package we're building for. Default to lqfp64 (Arduino Uno R4 Minima).
     * Future: read from a cargo feature flag
     */
    let package = "lqfp64";

    let pins = pin_file
        .pins
        .iter()
        .filter(|x| x.packages.iter().any(|y| y == package))
        .collect::<Vec<_>>();

    generate_pin_impls(&pins, &out_dir);
    generate_peripherals_list(&pins, &out_dir);
    generate_anypin_pfs(&pins, &out_dir);
}

/// Generates the impl_pin! / impl_input_only_pin! call sites.
/// Included in gpio.rs
fn generate_pin_impls(pins: &[&Pin], out_dir: &PathBuf) {
    let mut out = String::new();
    writeln!(out, "// Generated by build.rs - do not edit").unwrap();
    writeln!(out).unwrap();

    for pin in pins {
        let pfs_arg = pfs_argument(pin);
        if pin.input_only {
            writeln!(
                out,
                "impl_input_only_pin!({}, {}, {}, {}, {});",
                pin.name, pin.port_periph, pin.port, pin.pin, pfs_arg
            )
            .unwrap();
        } else {
            writeln!(
                out,
                "impl_pin!({}, {}, {}, {}, {});",
                pin.name, pin.port_periph, pin.port, pin.pin, pfs_arg
            )
            .unwrap();
        }
    }

    std::fs::write(out_dir.join("gpio_pin_impls.rs"), out).unwrap();
}

/// Generates the peripherals!(P100, P101, ...) invocation.
/// Included in lib.rs
fn generate_peripherals_list(pins: &[&Pin], out_dir: &PathBuf) {
    let mut out = String::new();
    writeln!(out, "// Generated by build.rs - do not edit").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "peripherals!(").unwrap();

    for pin in pins {
        writeln!(out, "    {},", pin.name).unwrap();
    }

    writeln!(out, ");").unwrap();
    std::fs::write(out_dir.join("peripherals.rs"), out).unwrap();
}

/// Generates AnyPin's PFS dispatch functions.
/// These take primitive parameters so the type heterogeneity between P000PFS_SPEC, P108PFS_SPEC,
/// etc. is handled per match arm.
/// Included in gpio.rs
fn generate_anypin_pfs(pins: &[&Pin], out_dir: &PathBuf) {
    let mut out = String::new();

    writeln!(out, "// Generated by build.rs - do not edit").unwrap();
    writeln!(
        out,
        "// AnyPin PFS dispatch - called from within with_pfs_unlocked()"
    )
    .unwrap();
    writeln!(out).unwrap();

    // configure input: sets PMR=0 and PCR per pull argument
    writeln!(out, "#[inline]").unwrap();
    writeln!(
        out,
        "fn anypin_pfs_configure_input(port: u8, pin_num: u8, pcr: bool) {{"
    )
    .unwrap();
    writeln!(out, "    let pfs = unsafe {{ &*crate::pac::PFS::PTR }};").unwrap();
    writeln!(out, "    match (port, pin_num) {{").unwrap();

    for pin in pins {
        let reg = pfs_register_expr(pin);
        writeln!(out, "        ({}, {}) => {}.write(|w| {{ if pcr {{ w.pcr()._1() }} else {{ w.pcr()._0() }}.pmr()._0() }}),", pin.port, pin.pin, reg).unwrap();
    }

    writeln!(out, "        _ => {{}}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // configure output: sets PMR=0 and DSCR from parameter
    writeln!(out, "#[inline]").unwrap();
    writeln!(
        out,
        "fn anypin_pfs_configure_output(port: u8, pin_num: u8, podr:bool, dscr: bool) {{"
    )
    .unwrap();
    writeln!(out, "    let pfs = unsafe {{ &*crate::pac::PFS::PTR }};").unwrap();
    writeln!(out, "    match (port, pin_num) {{").unwrap();

    for pin in pins {
        let reg = pfs_register_expr(pin);
        writeln!(
            out,
            "        ({}, {}) => {}.write(|w| w.pmr()._0().dscr().bit(dscr).podr().bit(podr).pdr()._1()),",
            pin.port, pin.pin, reg
        )
        .unwrap();
    }

    writeln!(out, "        _ => {{}}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // configure open drain
    writeln!(out, "#[inline]").unwrap();
    writeln!(out, "fn anypin_pfs_configure_open_drain(port: u8, pin_num: u8, pcr: bool,  podr: bool, dscr: bool) {{").unwrap();
    writeln!(out, "    let pfs = unsafe {{ &*crate::pac::PFS::PTR }};").unwrap();
    writeln!(out, "    match (port, pin_num) {{").unwrap();

    for pin in pins {
        let reg = pfs_register_expr(pin);
        writeln!(
            out,
            "        ({}, {}) => {}.write(|w| {{ if pcr {{ w.pcr()._1() }} else {{ w.pcr()._0() }} }}.pdr()._1().dscr().bit(dscr).podr().bit(podr).pmr()._0().ncodr()._1()),",
            pin.port, pin.pin, reg
        )
        .unwrap();
    }

    writeln!(out, "        _ => {{}}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // reset: restores all PFS fields to power-on defaults
    writeln!(out, "#[inline]").unwrap();
    writeln!(out, "fn anypin_pfs_reset(port: u8, pin_num: u8) {{").unwrap();
    writeln!(out, "    let pfs = unsafe {{ &*crate::pac::PFS::PTR }};").unwrap();
    writeln!(out, "    match (port, pin_num) {{").unwrap();

    for pin in pins {
        let reg = pfs_register_expr(pin);
        writeln!(
            out,
            "        ({}, {}) => {}.reset(),",
            pin.port, pin.pin, reg
        )
        .unwrap();
    }

    writeln!(out, "        _ => {{}}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    std::fs::write(out_dir.join("anypin_pfs.rs"), out).unwrap();
}

/// Return the macro argument for impl_pin!, e.g. "p100pfs\[0]" or "p111pfs"
fn pfs_argument(pin: &Pin) -> String {
    match pin.pfs_type.as_str() {
        "array" => format!("{}[{}]", pin.pfs_method, pin.pfs_index),
        "single" => pin.pfs_method.clone(),
        other => panic!("unknown pfs_type '{}' for pin {}", other, pin.name),
    }
}

/// Returns the register access expression for use in generated function bodies,
/// e.g. "pfs.p100pfs()\[0]" or "pfs.p111pfs()"
fn pfs_register_expr(pin: &Pin) -> String {
    match pin.pfs_type.as_str() {
        "array" => format!("pfs.{}()[{}]", pin.pfs_method, pin.pfs_index),
        "single" => format!("pfs.{}()", pin.pfs_method),
        other => panic!("unknown pfs_type '{}' for pin {}", other, pin.name),
    }
}
